server:
  port: 8089
spring:
  application:
    name: fegin-Hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:
    enabled: true #开启豪猪断路器


  #是否开启熔断器
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: true #是否开启熔断器
        requestVolumeThreshold: 2  #访问服务失败的次数，如果超过这个值熔断器就会打开，默认值20
        sleepWindowInMilliseconds: 2000 #指定时间内进入半开状态


